run:
  deadline: 5m

linters:
  enable-all: true
  disable:
    # deprecated
    - varnamelen
    - testpackage
    - golint
    - interfacer
    - structcheck
    - maligned
    - scopelint
    - nosnakecase
    - deadcode
    - varcheck
    - ifshort
    - exhaustivestruct
    - rowserrcheck
    - structcheck
    - wastedassign
    # meaningfully disabled
    - ireturn # returning generics
    - gochecknoglobals
    - exhaustruct
    - nosprintfhostport # not supporting ipv6 addresses in configuration

linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake
        yaml: camel
  revive:
    rules:
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: early-return
      - name: exported
        arguments: [ "checkPrivateReceivers" ]
      - name: unreachable-code
      - name: unused-receiver
      # default rules:
      - name: var-declaration
      - name: dot-imports
      - name: blank-imports
      - name: var-naming
      - name: indent-error-flow
      - name: range
      - name: errorf
      - name: receiver-naming
      - name: increment-decrement
      - name: error-return
      - name: time-naming
      - name: context-keys-type
      - name: context-as-argument

issues:
  exclude-use-default: false
  exclude-rules:
    - path: .+_test\.go
      linters:
        - bodyclose  # we use close it in a helper method
        - noctx
    - linters:
        - godox
      text: "TODO"
