with-expecter: true
all: true
recursive: false
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"
filename: "mock_{{.InterfaceName}}.go"
packages:
  github.com/outcatcher/scriba/internal/usecases:
  github.com/outcatcher/scriba/internal/bot/schema:
  github.com/outcatcher/scriba/internal/repo:
    config:
      all: false
    interfaces:
      queryExecutor:
  gopkg.in/telebot.v3:
    interfaces:
      Context:
    config:
      all: false
      dir: ./internal/bot/schema/mocks
