version: '3'

dotenv:
  - .env

vars:
  binary_path: "{{ .USER_WORKING_DIR }}/build/bot"
  migrate_path: "{{ .USER_WORKING_DIR }}/build/migrate"
  migrations_path: "{{ .USER_WORKING_DIR }}/internal/migrations"

tasks:
  help:
    silent: true
    cmd: task --list

  lint:
    desc: Run lint on the project
    cmd: golangci-lint run ./...

  generate:
    desc: Generate mocks
    cmds:
      - mockery

  test:
    desc: Run unit tests
    cmds:
      - go test -v -cover -covermode atomic -coverpkg=./internal/... -coverprofile=coverage.out -count=1 ./internal/...
      - grep -v -E -f .covignore coverage.out > coverage.filtered.out
      - mv coverage.filtered.out coverage.out
      - go tool cover -html=coverage.out -o coverage.html

  build:
    desc: Build app executable
    cmd: go build -trimpath -o "{{ .binary_path }}" ./cmd/bot/main.go

  build-migrate:
    desc: Build migration executable
    cmd: go build -trimpath -o "{{ .migrate_path }}" ./cmd/migrate/main.go

  run:
    desc: Run project with docker compose locally
    requires:
      vars:
        - BOT_TOKEN
        - POSTGRES_PASSWORD
        - POSTGRES_PORT
    cmd: docker compose up -d --build --wait

  check-deploy:
    desc: Run syntax check of the deployment
    dir: ./internal/deployment
    cmd: ansible-playbook --syntax-check deploy.yaml

  deploy:
    desc: Deploy project to the environment
    dir: ./internal/deployment
    requires:
      vars:
        - BOT_TOKEN
        - POSTGRES_PASSWORD
        - POSTGRES_PORT
        - VAULT_PASS
    deps:
      - build
      - build-migrate
    preconditions:
      - echo ${VAULT_PASS} > .vault_pass.txt
    cmd: >
      ansible-playbook
      --vault-pass-file .vault_pass.txt
      --extra-vars local_binary_path="{{ .binary_path }}"
      --extra-vars local_migrate_path="{{ .migrate_path }}"
      --extra-vars local_migrations_path="{{ .migrations_path }}"
      deploy.yaml
      -v
