- name: Validate required vars
  fail:
  when: item == ''
  loop:
    - local_binary_path
    - local_migrate_path
    - local_migrations_path

- name: Ensure deploy dir
  file:
    path: "{{ deploy_dir }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    mode: 0700
  become: yes

- name: Copy binary
  copy:
    src: "{{ local_binary_path }}"
    dest: "{{ deploy_dir }}/{{ binary_name }}"
    mode: 0700

- name: Copy migrate
  copy:
    src: "{{ local_migrate_path }}"
    dest: "{{ deploy_dir }}/migrate"
    mode: 0700

- name: Copy migrations
  copy:
    src: "{{ local_migrations_path }}"
    dest: "{{ deploy_dir }}"

- name: Copy templates
  template:
    src: "{{ item }}.j2"
    dest: "{{ deploy_dir }}/{{ item }}"
  loop:
    - app.Dockerfile
    - migrate.Dockerfile
    - docker-compose.yaml
    - config.yaml

- name: Docker compose down
  shell: "docker compose down"
  args:
    chdir: "{{ deploy_dir }}"

- name: Docker compose up
  shell: "docker compose up --build -d --wait"
  args:
    chdir: "{{ deploy_dir }}"
