storage:
  postgres:
    host: scriba-postgres
    port: 55631
    database: postgres
    username: postgres
    password: postgres

bot:
  method: poll # poll / webhook
  poll:
    interval: 3s
  webhook:
  messages:
    lifetime:
  verbose: yes
