deploy_dir: /opt/scriba
binary_name: scriba

postgres_port: "{{ lookup('env', 'POSTGRES_PORT') }}"
postgres_password: "{{ lookup('env', 'POSTGRES_PASSWORD') }}"
bot_token: "{{ lookup('env', 'BOT_TOKEN') }}"
bot_debug: no

docker_run_dir: "/run"
