// Code generated by mockery v2.34.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	telebot "gopkg.in/telebot.v3"

	time "time"
)

// MockContext is an autogenerated mock type for the Context type
type MockContext struct {
	mock.Mock
}

type MockContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContext) EXPECT() *MockContext_Expecter {
	return &MockContext_Expecter{mock: &_m.Mock}
}

// Accept provides a mock function with given fields: errorMessage
func (_m *MockContext) Accept(errorMessage ...string) error {
	_va := make([]interface{}, len(errorMessage))
	for _i := range errorMessage {
		_va[_i] = errorMessage[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...string) error); ok {
		r0 = rf(errorMessage...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Accept_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Accept'
type MockContext_Accept_Call struct {
	*mock.Call
}

// Accept is a helper method to define mock.On call
//   - errorMessage ...string
func (_e *MockContext_Expecter) Accept(errorMessage ...interface{}) *MockContext_Accept_Call {
	return &MockContext_Accept_Call{Call: _e.mock.On("Accept",
		append([]interface{}{}, errorMessage...)...)}
}

func (_c *MockContext_Accept_Call) Run(run func(errorMessage ...string)) *MockContext_Accept_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Accept_Call) Return(_a0 error) *MockContext_Accept_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Accept_Call) RunAndReturn(run func(...string) error) *MockContext_Accept_Call {
	_c.Call.Return(run)
	return _c
}

// Answer provides a mock function with given fields: resp
func (_m *MockContext) Answer(resp *telebot.QueryResponse) error {
	ret := _m.Called(resp)

	var r0 error
	if rf, ok := ret.Get(0).(func(*telebot.QueryResponse) error); ok {
		r0 = rf(resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Answer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Answer'
type MockContext_Answer_Call struct {
	*mock.Call
}

// Answer is a helper method to define mock.On call
//   - resp *telebot.QueryResponse
func (_e *MockContext_Expecter) Answer(resp interface{}) *MockContext_Answer_Call {
	return &MockContext_Answer_Call{Call: _e.mock.On("Answer", resp)}
}

func (_c *MockContext_Answer_Call) Run(run func(resp *telebot.QueryResponse)) *MockContext_Answer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*telebot.QueryResponse))
	})
	return _c
}

func (_c *MockContext_Answer_Call) Return(_a0 error) *MockContext_Answer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Answer_Call) RunAndReturn(run func(*telebot.QueryResponse) error) *MockContext_Answer_Call {
	_c.Call.Return(run)
	return _c
}

// Args provides a mock function with given fields:
func (_m *MockContext) Args() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockContext_Args_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Args'
type MockContext_Args_Call struct {
	*mock.Call
}

// Args is a helper method to define mock.On call
func (_e *MockContext_Expecter) Args() *MockContext_Args_Call {
	return &MockContext_Args_Call{Call: _e.mock.On("Args")}
}

func (_c *MockContext_Args_Call) Run(run func()) *MockContext_Args_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Args_Call) Return(_a0 []string) *MockContext_Args_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Args_Call) RunAndReturn(run func() []string) *MockContext_Args_Call {
	_c.Call.Return(run)
	return _c
}

// Bot provides a mock function with given fields:
func (_m *MockContext) Bot() *telebot.Bot {
	ret := _m.Called()

	var r0 *telebot.Bot
	if rf, ok := ret.Get(0).(func() *telebot.Bot); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Bot)
		}
	}

	return r0
}

// MockContext_Bot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bot'
type MockContext_Bot_Call struct {
	*mock.Call
}

// Bot is a helper method to define mock.On call
func (_e *MockContext_Expecter) Bot() *MockContext_Bot_Call {
	return &MockContext_Bot_Call{Call: _e.mock.On("Bot")}
}

func (_c *MockContext_Bot_Call) Run(run func()) *MockContext_Bot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Bot_Call) Return(_a0 *telebot.Bot) *MockContext_Bot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Bot_Call) RunAndReturn(run func() *telebot.Bot) *MockContext_Bot_Call {
	_c.Call.Return(run)
	return _c
}

// Callback provides a mock function with given fields:
func (_m *MockContext) Callback() *telebot.Callback {
	ret := _m.Called()

	var r0 *telebot.Callback
	if rf, ok := ret.Get(0).(func() *telebot.Callback); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Callback)
		}
	}

	return r0
}

// MockContext_Callback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Callback'
type MockContext_Callback_Call struct {
	*mock.Call
}

// Callback is a helper method to define mock.On call
func (_e *MockContext_Expecter) Callback() *MockContext_Callback_Call {
	return &MockContext_Callback_Call{Call: _e.mock.On("Callback")}
}

func (_c *MockContext_Callback_Call) Run(run func()) *MockContext_Callback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Callback_Call) Return(_a0 *telebot.Callback) *MockContext_Callback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Callback_Call) RunAndReturn(run func() *telebot.Callback) *MockContext_Callback_Call {
	_c.Call.Return(run)
	return _c
}

// Chat provides a mock function with given fields:
func (_m *MockContext) Chat() *telebot.Chat {
	ret := _m.Called()

	var r0 *telebot.Chat
	if rf, ok := ret.Get(0).(func() *telebot.Chat); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Chat)
		}
	}

	return r0
}

// MockContext_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type MockContext_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
func (_e *MockContext_Expecter) Chat() *MockContext_Chat_Call {
	return &MockContext_Chat_Call{Call: _e.mock.On("Chat")}
}

func (_c *MockContext_Chat_Call) Run(run func()) *MockContext_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Chat_Call) Return(_a0 *telebot.Chat) *MockContext_Chat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Chat_Call) RunAndReturn(run func() *telebot.Chat) *MockContext_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// ChatJoinRequest provides a mock function with given fields:
func (_m *MockContext) ChatJoinRequest() *telebot.ChatJoinRequest {
	ret := _m.Called()

	var r0 *telebot.ChatJoinRequest
	if rf, ok := ret.Get(0).(func() *telebot.ChatJoinRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ChatJoinRequest)
		}
	}

	return r0
}

// MockContext_ChatJoinRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatJoinRequest'
type MockContext_ChatJoinRequest_Call struct {
	*mock.Call
}

// ChatJoinRequest is a helper method to define mock.On call
func (_e *MockContext_Expecter) ChatJoinRequest() *MockContext_ChatJoinRequest_Call {
	return &MockContext_ChatJoinRequest_Call{Call: _e.mock.On("ChatJoinRequest")}
}

func (_c *MockContext_ChatJoinRequest_Call) Run(run func()) *MockContext_ChatJoinRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ChatJoinRequest_Call) Return(_a0 *telebot.ChatJoinRequest) *MockContext_ChatJoinRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_ChatJoinRequest_Call) RunAndReturn(run func() *telebot.ChatJoinRequest) *MockContext_ChatJoinRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ChatMember provides a mock function with given fields:
func (_m *MockContext) ChatMember() *telebot.ChatMemberUpdate {
	ret := _m.Called()

	var r0 *telebot.ChatMemberUpdate
	if rf, ok := ret.Get(0).(func() *telebot.ChatMemberUpdate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ChatMemberUpdate)
		}
	}

	return r0
}

// MockContext_ChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChatMember'
type MockContext_ChatMember_Call struct {
	*mock.Call
}

// ChatMember is a helper method to define mock.On call
func (_e *MockContext_Expecter) ChatMember() *MockContext_ChatMember_Call {
	return &MockContext_ChatMember_Call{Call: _e.mock.On("ChatMember")}
}

func (_c *MockContext_ChatMember_Call) Run(run func()) *MockContext_ChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ChatMember_Call) Return(_a0 *telebot.ChatMemberUpdate) *MockContext_ChatMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_ChatMember_Call) RunAndReturn(run func() *telebot.ChatMemberUpdate) *MockContext_ChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function with given fields:
func (_m *MockContext) Data() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockContext_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockContext_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *MockContext_Expecter) Data() *MockContext_Data_Call {
	return &MockContext_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *MockContext_Data_Call) Run(run func()) *MockContext_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Data_Call) Return(_a0 string) *MockContext_Data_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Data_Call) RunAndReturn(run func() string) *MockContext_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields:
func (_m *MockContext) Delete() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockContext_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
func (_e *MockContext_Expecter) Delete() *MockContext_Delete_Call {
	return &MockContext_Delete_Call{Call: _e.mock.On("Delete")}
}

func (_c *MockContext_Delete_Call) Run(run func()) *MockContext_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Delete_Call) Return(_a0 error) *MockContext_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Delete_Call) RunAndReturn(run func() error) *MockContext_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAfter provides a mock function with given fields: d
func (_m *MockContext) DeleteAfter(d time.Duration) *time.Timer {
	ret := _m.Called(d)

	var r0 *time.Timer
	if rf, ok := ret.Get(0).(func(time.Duration) *time.Timer); ok {
		r0 = rf(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Timer)
		}
	}

	return r0
}

// MockContext_DeleteAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAfter'
type MockContext_DeleteAfter_Call struct {
	*mock.Call
}

// DeleteAfter is a helper method to define mock.On call
//   - d time.Duration
func (_e *MockContext_Expecter) DeleteAfter(d interface{}) *MockContext_DeleteAfter_Call {
	return &MockContext_DeleteAfter_Call{Call: _e.mock.On("DeleteAfter", d)}
}

func (_c *MockContext_DeleteAfter_Call) Run(run func(d time.Duration)) *MockContext_DeleteAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration))
	})
	return _c
}

func (_c *MockContext_DeleteAfter_Call) Return(_a0 *time.Timer) *MockContext_DeleteAfter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_DeleteAfter_Call) RunAndReturn(run func(time.Duration) *time.Timer) *MockContext_DeleteAfter_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function with given fields: what, opts
func (_m *MockContext) Edit(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockContext_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) Edit(what interface{}, opts ...interface{}) *MockContext_Edit_Call {
	return &MockContext_Edit_Call{Call: _e.mock.On("Edit",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_Edit_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Edit_Call) Return(_a0 error) *MockContext_Edit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Edit_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *MockContext_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// EditCaption provides a mock function with given fields: caption, opts
func (_m *MockContext) EditCaption(caption string, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, caption)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = rf(caption, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_EditCaption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditCaption'
type MockContext_EditCaption_Call struct {
	*mock.Call
}

// EditCaption is a helper method to define mock.On call
//   - caption string
//   - opts ...interface{}
func (_e *MockContext_Expecter) EditCaption(caption interface{}, opts ...interface{}) *MockContext_EditCaption_Call {
	return &MockContext_EditCaption_Call{Call: _e.mock.On("EditCaption",
		append([]interface{}{caption}, opts...)...)}
}

func (_c *MockContext_EditCaption_Call) Run(run func(caption string, opts ...interface{})) *MockContext_EditCaption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_EditCaption_Call) Return(_a0 error) *MockContext_EditCaption_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_EditCaption_Call) RunAndReturn(run func(string, ...interface{}) error) *MockContext_EditCaption_Call {
	_c.Call.Return(run)
	return _c
}

// EditOrReply provides a mock function with given fields: what, opts
func (_m *MockContext) EditOrReply(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_EditOrReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOrReply'
type MockContext_EditOrReply_Call struct {
	*mock.Call
}

// EditOrReply is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) EditOrReply(what interface{}, opts ...interface{}) *MockContext_EditOrReply_Call {
	return &MockContext_EditOrReply_Call{Call: _e.mock.On("EditOrReply",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_EditOrReply_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_EditOrReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_EditOrReply_Call) Return(_a0 error) *MockContext_EditOrReply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_EditOrReply_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *MockContext_EditOrReply_Call {
	_c.Call.Return(run)
	return _c
}

// EditOrSend provides a mock function with given fields: what, opts
func (_m *MockContext) EditOrSend(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_EditOrSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditOrSend'
type MockContext_EditOrSend_Call struct {
	*mock.Call
}

// EditOrSend is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) EditOrSend(what interface{}, opts ...interface{}) *MockContext_EditOrSend_Call {
	return &MockContext_EditOrSend_Call{Call: _e.mock.On("EditOrSend",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_EditOrSend_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_EditOrSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_EditOrSend_Call) Return(_a0 error) *MockContext_EditOrSend_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_EditOrSend_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *MockContext_EditOrSend_Call {
	_c.Call.Return(run)
	return _c
}

// Entities provides a mock function with given fields:
func (_m *MockContext) Entities() telebot.Entities {
	ret := _m.Called()

	var r0 telebot.Entities
	if rf, ok := ret.Get(0).(func() telebot.Entities); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.Entities)
		}
	}

	return r0
}

// MockContext_Entities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entities'
type MockContext_Entities_Call struct {
	*mock.Call
}

// Entities is a helper method to define mock.On call
func (_e *MockContext_Expecter) Entities() *MockContext_Entities_Call {
	return &MockContext_Entities_Call{Call: _e.mock.On("Entities")}
}

func (_c *MockContext_Entities_Call) Run(run func()) *MockContext_Entities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Entities_Call) Return(_a0 telebot.Entities) *MockContext_Entities_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Entities_Call) RunAndReturn(run func() telebot.Entities) *MockContext_Entities_Call {
	_c.Call.Return(run)
	return _c
}

// Forward provides a mock function with given fields: msg, opts
func (_m *MockContext) Forward(msg telebot.Editable, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.Editable, ...interface{}) error); ok {
		r0 = rf(msg, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Forward_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Forward'
type MockContext_Forward_Call struct {
	*mock.Call
}

// Forward is a helper method to define mock.On call
//   - msg telebot.Editable
//   - opts ...interface{}
func (_e *MockContext_Expecter) Forward(msg interface{}, opts ...interface{}) *MockContext_Forward_Call {
	return &MockContext_Forward_Call{Call: _e.mock.On("Forward",
		append([]interface{}{msg}, opts...)...)}
}

func (_c *MockContext_Forward_Call) Run(run func(msg telebot.Editable, opts ...interface{})) *MockContext_Forward_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(telebot.Editable), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Forward_Call) Return(_a0 error) *MockContext_Forward_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Forward_Call) RunAndReturn(run func(telebot.Editable, ...interface{}) error) *MockContext_Forward_Call {
	_c.Call.Return(run)
	return _c
}

// ForwardTo provides a mock function with given fields: to, opts
func (_m *MockContext) ForwardTo(to telebot.Recipient, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, to)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.Recipient, ...interface{}) error); ok {
		r0 = rf(to, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_ForwardTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForwardTo'
type MockContext_ForwardTo_Call struct {
	*mock.Call
}

// ForwardTo is a helper method to define mock.On call
//   - to telebot.Recipient
//   - opts ...interface{}
func (_e *MockContext_Expecter) ForwardTo(to interface{}, opts ...interface{}) *MockContext_ForwardTo_Call {
	return &MockContext_ForwardTo_Call{Call: _e.mock.On("ForwardTo",
		append([]interface{}{to}, opts...)...)}
}

func (_c *MockContext_ForwardTo_Call) Run(run func(to telebot.Recipient, opts ...interface{})) *MockContext_ForwardTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(telebot.Recipient), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_ForwardTo_Call) Return(_a0 error) *MockContext_ForwardTo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_ForwardTo_Call) RunAndReturn(run func(telebot.Recipient, ...interface{}) error) *MockContext_ForwardTo_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: key
func (_m *MockContext) Get(key string) interface{} {
	ret := _m.Called(key)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockContext_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContext_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockContext_Expecter) Get(key interface{}) *MockContext_Get_Call {
	return &MockContext_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockContext_Get_Call) Run(run func(key string)) *MockContext_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockContext_Get_Call) Return(_a0 interface{}) *MockContext_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Get_Call) RunAndReturn(run func(string) interface{}) *MockContext_Get_Call {
	_c.Call.Return(run)
	return _c
}

// InlineResult provides a mock function with given fields:
func (_m *MockContext) InlineResult() *telebot.InlineResult {
	ret := _m.Called()

	var r0 *telebot.InlineResult
	if rf, ok := ret.Get(0).(func() *telebot.InlineResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.InlineResult)
		}
	}

	return r0
}

// MockContext_InlineResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InlineResult'
type MockContext_InlineResult_Call struct {
	*mock.Call
}

// InlineResult is a helper method to define mock.On call
func (_e *MockContext_Expecter) InlineResult() *MockContext_InlineResult_Call {
	return &MockContext_InlineResult_Call{Call: _e.mock.On("InlineResult")}
}

func (_c *MockContext_InlineResult_Call) Run(run func()) *MockContext_InlineResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_InlineResult_Call) Return(_a0 *telebot.InlineResult) *MockContext_InlineResult_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_InlineResult_Call) RunAndReturn(run func() *telebot.InlineResult) *MockContext_InlineResult_Call {
	_c.Call.Return(run)
	return _c
}

// Message provides a mock function with given fields:
func (_m *MockContext) Message() *telebot.Message {
	ret := _m.Called()

	var r0 *telebot.Message
	if rf, ok := ret.Get(0).(func() *telebot.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Message)
		}
	}

	return r0
}

// MockContext_Message_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Message'
type MockContext_Message_Call struct {
	*mock.Call
}

// Message is a helper method to define mock.On call
func (_e *MockContext_Expecter) Message() *MockContext_Message_Call {
	return &MockContext_Message_Call{Call: _e.mock.On("Message")}
}

func (_c *MockContext_Message_Call) Run(run func()) *MockContext_Message_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Message_Call) Return(_a0 *telebot.Message) *MockContext_Message_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Message_Call) RunAndReturn(run func() *telebot.Message) *MockContext_Message_Call {
	_c.Call.Return(run)
	return _c
}

// Migration provides a mock function with given fields:
func (_m *MockContext) Migration() (int64, int64) {
	ret := _m.Called()

	var r0 int64
	var r1 int64
	if rf, ok := ret.Get(0).(func() (int64, int64)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func() int64); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(int64)
	}

	return r0, r1
}

// MockContext_Migration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migration'
type MockContext_Migration_Call struct {
	*mock.Call
}

// Migration is a helper method to define mock.On call
func (_e *MockContext_Expecter) Migration() *MockContext_Migration_Call {
	return &MockContext_Migration_Call{Call: _e.mock.On("Migration")}
}

func (_c *MockContext_Migration_Call) Run(run func()) *MockContext_Migration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Migration_Call) Return(_a0 int64, _a1 int64) *MockContext_Migration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContext_Migration_Call) RunAndReturn(run func() (int64, int64)) *MockContext_Migration_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function with given fields: action
func (_m *MockContext) Notify(action telebot.ChatAction) error {
	ret := _m.Called(action)

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.ChatAction) error); ok {
		r0 = rf(action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockContext_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - action telebot.ChatAction
func (_e *MockContext_Expecter) Notify(action interface{}) *MockContext_Notify_Call {
	return &MockContext_Notify_Call{Call: _e.mock.On("Notify", action)}
}

func (_c *MockContext_Notify_Call) Run(run func(action telebot.ChatAction)) *MockContext_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(telebot.ChatAction))
	})
	return _c
}

func (_c *MockContext_Notify_Call) Return(_a0 error) *MockContext_Notify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Notify_Call) RunAndReturn(run func(telebot.ChatAction) error) *MockContext_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// Poll provides a mock function with given fields:
func (_m *MockContext) Poll() *telebot.Poll {
	ret := _m.Called()

	var r0 *telebot.Poll
	if rf, ok := ret.Get(0).(func() *telebot.Poll); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Poll)
		}
	}

	return r0
}

// MockContext_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockContext_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
func (_e *MockContext_Expecter) Poll() *MockContext_Poll_Call {
	return &MockContext_Poll_Call{Call: _e.mock.On("Poll")}
}

func (_c *MockContext_Poll_Call) Run(run func()) *MockContext_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Poll_Call) Return(_a0 *telebot.Poll) *MockContext_Poll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Poll_Call) RunAndReturn(run func() *telebot.Poll) *MockContext_Poll_Call {
	_c.Call.Return(run)
	return _c
}

// PollAnswer provides a mock function with given fields:
func (_m *MockContext) PollAnswer() *telebot.PollAnswer {
	ret := _m.Called()

	var r0 *telebot.PollAnswer
	if rf, ok := ret.Get(0).(func() *telebot.PollAnswer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PollAnswer)
		}
	}

	return r0
}

// MockContext_PollAnswer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollAnswer'
type MockContext_PollAnswer_Call struct {
	*mock.Call
}

// PollAnswer is a helper method to define mock.On call
func (_e *MockContext_Expecter) PollAnswer() *MockContext_PollAnswer_Call {
	return &MockContext_PollAnswer_Call{Call: _e.mock.On("PollAnswer")}
}

func (_c *MockContext_PollAnswer_Call) Run(run func()) *MockContext_PollAnswer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_PollAnswer_Call) Return(_a0 *telebot.PollAnswer) *MockContext_PollAnswer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_PollAnswer_Call) RunAndReturn(run func() *telebot.PollAnswer) *MockContext_PollAnswer_Call {
	_c.Call.Return(run)
	return _c
}

// PreCheckoutQuery provides a mock function with given fields:
func (_m *MockContext) PreCheckoutQuery() *telebot.PreCheckoutQuery {
	ret := _m.Called()

	var r0 *telebot.PreCheckoutQuery
	if rf, ok := ret.Get(0).(func() *telebot.PreCheckoutQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.PreCheckoutQuery)
		}
	}

	return r0
}

// MockContext_PreCheckoutQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreCheckoutQuery'
type MockContext_PreCheckoutQuery_Call struct {
	*mock.Call
}

// PreCheckoutQuery is a helper method to define mock.On call
func (_e *MockContext_Expecter) PreCheckoutQuery() *MockContext_PreCheckoutQuery_Call {
	return &MockContext_PreCheckoutQuery_Call{Call: _e.mock.On("PreCheckoutQuery")}
}

func (_c *MockContext_PreCheckoutQuery_Call) Run(run func()) *MockContext_PreCheckoutQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_PreCheckoutQuery_Call) Return(_a0 *telebot.PreCheckoutQuery) *MockContext_PreCheckoutQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_PreCheckoutQuery_Call) RunAndReturn(run func() *telebot.PreCheckoutQuery) *MockContext_PreCheckoutQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields:
func (_m *MockContext) Query() *telebot.Query {
	ret := _m.Called()

	var r0 *telebot.Query
	if rf, ok := ret.Get(0).(func() *telebot.Query); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Query)
		}
	}

	return r0
}

// MockContext_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockContext_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
func (_e *MockContext_Expecter) Query() *MockContext_Query_Call {
	return &MockContext_Query_Call{Call: _e.mock.On("Query")}
}

func (_c *MockContext_Query_Call) Run(run func()) *MockContext_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Query_Call) Return(_a0 *telebot.Query) *MockContext_Query_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Query_Call) RunAndReturn(run func() *telebot.Query) *MockContext_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Recipient provides a mock function with given fields:
func (_m *MockContext) Recipient() telebot.Recipient {
	ret := _m.Called()

	var r0 telebot.Recipient
	if rf, ok := ret.Get(0).(func() telebot.Recipient); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(telebot.Recipient)
		}
	}

	return r0
}

// MockContext_Recipient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recipient'
type MockContext_Recipient_Call struct {
	*mock.Call
}

// Recipient is a helper method to define mock.On call
func (_e *MockContext_Expecter) Recipient() *MockContext_Recipient_Call {
	return &MockContext_Recipient_Call{Call: _e.mock.On("Recipient")}
}

func (_c *MockContext_Recipient_Call) Run(run func()) *MockContext_Recipient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Recipient_Call) Return(_a0 telebot.Recipient) *MockContext_Recipient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Recipient_Call) RunAndReturn(run func() telebot.Recipient) *MockContext_Recipient_Call {
	_c.Call.Return(run)
	return _c
}

// Reply provides a mock function with given fields: what, opts
func (_m *MockContext) Reply(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Reply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reply'
type MockContext_Reply_Call struct {
	*mock.Call
}

// Reply is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) Reply(what interface{}, opts ...interface{}) *MockContext_Reply_Call {
	return &MockContext_Reply_Call{Call: _e.mock.On("Reply",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_Reply_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_Reply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Reply_Call) Return(_a0 error) *MockContext_Reply_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Reply_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *MockContext_Reply_Call {
	_c.Call.Return(run)
	return _c
}

// Respond provides a mock function with given fields: resp
func (_m *MockContext) Respond(resp ...*telebot.CallbackResponse) error {
	_va := make([]interface{}, len(resp))
	for _i := range resp {
		_va[_i] = resp[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*telebot.CallbackResponse) error); ok {
		r0 = rf(resp...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type MockContext_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - resp ...*telebot.CallbackResponse
func (_e *MockContext_Expecter) Respond(resp ...interface{}) *MockContext_Respond_Call {
	return &MockContext_Respond_Call{Call: _e.mock.On("Respond",
		append([]interface{}{}, resp...)...)}
}

func (_c *MockContext_Respond_Call) Run(run func(resp ...*telebot.CallbackResponse)) *MockContext_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]*telebot.CallbackResponse, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(*telebot.CallbackResponse)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Respond_Call) Return(_a0 error) *MockContext_Respond_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Respond_Call) RunAndReturn(run func(...*telebot.CallbackResponse) error) *MockContext_Respond_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: what, opts
func (_m *MockContext) Send(what interface{}, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, ...interface{}) error); ok {
		r0 = rf(what, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockContext_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - what interface{}
//   - opts ...interface{}
func (_e *MockContext_Expecter) Send(what interface{}, opts ...interface{}) *MockContext_Send_Call {
	return &MockContext_Send_Call{Call: _e.mock.On("Send",
		append([]interface{}{what}, opts...)...)}
}

func (_c *MockContext_Send_Call) Run(run func(what interface{}, opts ...interface{})) *MockContext_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Send_Call) Return(_a0 error) *MockContext_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Send_Call) RunAndReturn(run func(interface{}, ...interface{}) error) *MockContext_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendAlbum provides a mock function with given fields: a, opts
func (_m *MockContext) SendAlbum(a telebot.Album, opts ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, a)
	_ca = append(_ca, opts...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(telebot.Album, ...interface{}) error); ok {
		r0 = rf(a, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_SendAlbum_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAlbum'
type MockContext_SendAlbum_Call struct {
	*mock.Call
}

// SendAlbum is a helper method to define mock.On call
//   - a telebot.Album
//   - opts ...interface{}
func (_e *MockContext_Expecter) SendAlbum(a interface{}, opts ...interface{}) *MockContext_SendAlbum_Call {
	return &MockContext_SendAlbum_Call{Call: _e.mock.On("SendAlbum",
		append([]interface{}{a}, opts...)...)}
}

func (_c *MockContext_SendAlbum_Call) Run(run func(a telebot.Album, opts ...interface{})) *MockContext_SendAlbum_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(telebot.Album), variadicArgs...)
	})
	return _c
}

func (_c *MockContext_SendAlbum_Call) Return(_a0 error) *MockContext_SendAlbum_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_SendAlbum_Call) RunAndReturn(run func(telebot.Album, ...interface{}) error) *MockContext_SendAlbum_Call {
	_c.Call.Return(run)
	return _c
}

// Sender provides a mock function with given fields:
func (_m *MockContext) Sender() *telebot.User {
	ret := _m.Called()

	var r0 *telebot.User
	if rf, ok := ret.Get(0).(func() *telebot.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.User)
		}
	}

	return r0
}

// MockContext_Sender_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sender'
type MockContext_Sender_Call struct {
	*mock.Call
}

// Sender is a helper method to define mock.On call
func (_e *MockContext_Expecter) Sender() *MockContext_Sender_Call {
	return &MockContext_Sender_Call{Call: _e.mock.On("Sender")}
}

func (_c *MockContext_Sender_Call) Run(run func()) *MockContext_Sender_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Sender_Call) Return(_a0 *telebot.User) *MockContext_Sender_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Sender_Call) RunAndReturn(run func() *telebot.User) *MockContext_Sender_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, val
func (_m *MockContext) Set(key string, val interface{}) {
	_m.Called(key, val)
}

// MockContext_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockContext_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - val interface{}
func (_e *MockContext_Expecter) Set(key interface{}, val interface{}) *MockContext_Set_Call {
	return &MockContext_Set_Call{Call: _e.mock.On("Set", key, val)}
}

func (_c *MockContext_Set_Call) Run(run func(key string, val interface{})) *MockContext_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *MockContext_Set_Call) Return() *MockContext_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContext_Set_Call) RunAndReturn(run func(string, interface{})) *MockContext_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Ship provides a mock function with given fields: what
func (_m *MockContext) Ship(what ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, what...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(what...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContext_Ship_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ship'
type MockContext_Ship_Call struct {
	*mock.Call
}

// Ship is a helper method to define mock.On call
//   - what ...interface{}
func (_e *MockContext_Expecter) Ship(what ...interface{}) *MockContext_Ship_Call {
	return &MockContext_Ship_Call{Call: _e.mock.On("Ship",
		append([]interface{}{}, what...)...)}
}

func (_c *MockContext_Ship_Call) Run(run func(what ...interface{})) *MockContext_Ship_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockContext_Ship_Call) Return(_a0 error) *MockContext_Ship_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Ship_Call) RunAndReturn(run func(...interface{}) error) *MockContext_Ship_Call {
	_c.Call.Return(run)
	return _c
}

// ShippingQuery provides a mock function with given fields:
func (_m *MockContext) ShippingQuery() *telebot.ShippingQuery {
	ret := _m.Called()

	var r0 *telebot.ShippingQuery
	if rf, ok := ret.Get(0).(func() *telebot.ShippingQuery); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.ShippingQuery)
		}
	}

	return r0
}

// MockContext_ShippingQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShippingQuery'
type MockContext_ShippingQuery_Call struct {
	*mock.Call
}

// ShippingQuery is a helper method to define mock.On call
func (_e *MockContext_Expecter) ShippingQuery() *MockContext_ShippingQuery_Call {
	return &MockContext_ShippingQuery_Call{Call: _e.mock.On("ShippingQuery")}
}

func (_c *MockContext_ShippingQuery_Call) Run(run func()) *MockContext_ShippingQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_ShippingQuery_Call) Return(_a0 *telebot.ShippingQuery) *MockContext_ShippingQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_ShippingQuery_Call) RunAndReturn(run func() *telebot.ShippingQuery) *MockContext_ShippingQuery_Call {
	_c.Call.Return(run)
	return _c
}

// Text provides a mock function with given fields:
func (_m *MockContext) Text() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockContext_Text_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Text'
type MockContext_Text_Call struct {
	*mock.Call
}

// Text is a helper method to define mock.On call
func (_e *MockContext_Expecter) Text() *MockContext_Text_Call {
	return &MockContext_Text_Call{Call: _e.mock.On("Text")}
}

func (_c *MockContext_Text_Call) Run(run func()) *MockContext_Text_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Text_Call) Return(_a0 string) *MockContext_Text_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Text_Call) RunAndReturn(run func() string) *MockContext_Text_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with given fields:
func (_m *MockContext) Topic() *telebot.Topic {
	ret := _m.Called()

	var r0 *telebot.Topic
	if rf, ok := ret.Get(0).(func() *telebot.Topic); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*telebot.Topic)
		}
	}

	return r0
}

// MockContext_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockContext_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockContext_Expecter) Topic() *MockContext_Topic_Call {
	return &MockContext_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockContext_Topic_Call) Run(run func()) *MockContext_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Topic_Call) Return(_a0 *telebot.Topic) *MockContext_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Topic_Call) RunAndReturn(run func() *telebot.Topic) *MockContext_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields:
func (_m *MockContext) Update() telebot.Update {
	ret := _m.Called()

	var r0 telebot.Update
	if rf, ok := ret.Get(0).(func() telebot.Update); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(telebot.Update)
	}

	return r0
}

// MockContext_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContext_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
func (_e *MockContext_Expecter) Update() *MockContext_Update_Call {
	return &MockContext_Update_Call{Call: _e.mock.On("Update")}
}

func (_c *MockContext_Update_Call) Run(run func()) *MockContext_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContext_Update_Call) Return(_a0 telebot.Update) *MockContext_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContext_Update_Call) RunAndReturn(run func() telebot.Update) *MockContext_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContext creates a new instance of MockContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContext {
	mock := &MockContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
